### PR TITLE
Player fixes/polishing

### PR DESCRIPTION
**Pull request by BuyMyBeard**
### Bugfixes: 

- #3
- #36
- #47 
- #48
- #53
- #54 
- #55 
- #28
- #62 
- Tuned Light Attack combo speed
- Fixed a bug where holding sprint button while locked on and not moving wouldn't turn the player towards the enemy
- Fixed a bug where the player would remain stuck blocking
- Fixed a bug where the first input was not registered for pause and sprint
- Fixed a bug where rotating the player in edit mode would cause the lock-on angle to not be straight
- Fixed bugs with pause and rest menus allowing other inputs to go through when resuming
- Fixed a bug where the player would not complete his interaction animation upon resting at an arcade cabinet
- Fixed Interact prompt not displaying the right key
- Fixed bosses not going into their pose when recharging at an arcade cabinet
- Fixed bosses not doing their special attack when reaching 50% hp
- Fixed enemies sometimes not doing their death animation when getting killed (zombie mode)
- Fixed a bug where the cursor disappears when trying to switch lock-on target unsuccessfully
- Fixed a bug where you could lock-on to an enemy behind you

### New Features

- Guard Break (Running out of stamina while blocking)
- Fall
- Screen shake for bosses special attacks
- Display bars linger now always moves at a fixed speed instead of a fixed time
- Implemented #57

### CODE REVIEW

**Comment by BuyMyBeard** [comment]
4337a4be75e9ae8cfc1af605dd4bdc00

**Comment by BuyMyBeard** [comment]
dancing-voting-day

**Review by JohnP55 — APPROVED** [review]

**Review by JeremyDeschamps — APPROVED** [review]
Y shit Thats some Content BABYYY 
wooo-yeah-baby

**Review by Dzubrul — APPROVED** [review]
We GUCCI
image

**Pull request merged**
